@startuml

title __ASSIST's Class Diagram__\n

  namespace dev.widget {
    namespace assist {
      class dev.widget.assist.ViewAssist {
          {static} + TYPE_EMPTY_DATA : int
          {static} + TYPE_FAILED : int
          {static} + TYPE_ING : int
          {static} + TYPE_SUCCESS : int
          - mCurrentType : int
          - mCurrentView : View
          - mData : Object
          - mMapAdapters : HashMap<Integer, Adapter>
          - mMapDatas : HashMap<String, Object>
          - mTag : String
          - mTypeViews : SparseArray<View>
          - mWrapper : ViewGroup
          + getAdapter()
          + getCurrentType()
          + getCurrentView()
          + getData()
          + getData()
          + getTag()
          + getView()
          + getWrapper()
          + gone()
          + notifyDataSetChanged()
          + register()
          + reset()
          + setData()
          + setData()
          + setListener()
          + setTag()
          + showEmptyData()
          + showFailed()
          + showIng()
          + showSuccess()
          + showType()
          + unregister()
          + unregister()
          + visible()
          {static} + wrap()
          {static} + wrap()
          - ViewAssist()
      }
    }
  }
  

  namespace dev.widget {
    namespace assist {
      interface dev.widget.assist.ViewAssist.Adapter {
          {abstract} + onBindView()
          {abstract} + onCreateView()
      }
    }
  }
  

  namespace dev.widget {
    namespace assist {
      interface dev.widget.assist.ViewAssist.Listener {
          {abstract} + onChange()
          {abstract} + onNotFound()
          {abstract} + onRemove()
      }
    }
  }
  

  dev.widget.assist.ViewAssist o-- dev.widget.assist.ViewAssist.Listener : mListener
  dev.widget.assist.ViewAssist +-down- dev.widget.assist.ViewAssist.Adapter
  dev.widget.assist.ViewAssist +-down- dev.widget.assist.ViewAssist.Listener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
