@startuml

title __TOAST's Class Diagram__\n

  namespace utils_use.toast {
    class utils_use.toast.DevToastUse {
        {static} - view : View
        {static} - viewId : int
        {static} + toastUse()
        - DevToastUse()
        - toastConfig()
    }
  }
  

  namespace utils_use.toast {
    class utils_use.toast.DevToastUse.TempStyle {
        + getBackground()
        + getBackgroundTintColor()
        + getCornerRadius()
        + getEllipsize()
        + getGravity()
        + getHorizontalMargin()
        + getMaxLines()
        + getPadding()
        + getTextColor()
        + getTextSize()
        + getTypeface()
        + getVerticalMargin()
        + getXOffset()
        + getYOffset()
        + getZ()
    }
  }
  

  namespace utils_use.toast {
    class utils_use.toast.ToastTintUse {
        {static} - iconDrawable : Drawable
        {static} - style : Style
        {static} + toastUse()
        - ToastTintUse()
        - toastConfig()
    }
  }
  

  namespace utils_use.toast {
    class utils_use.toast.ToastTintUse.TempStyle {
        + getBackground()
        + getBackgroundTintColor()
        + getEllipsize()
        + getMaxLines()
        + getTextColor()
        + getTextSize()
        + getTintIconColor()
        + getTypeface()
        + isTintIcon()
    }
  }
  

  utils_use.toast.DevToastUse +-down- utils_use.toast.DevToastUse.TempStyle
  utils_use.toast.DevToastUse.TempStyle .up.|> dev.utils.app.toast.toaster.IToast.Style
  utils_use.toast.ToastTintUse +-down- utils_use.toast.ToastTintUse.TempStyle
  utils_use.toast.ToastTintUse.TempStyle .up.|> dev.utils.app.toast.ToastTintUtils.Style


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
