@startuml

title __IMAGE's Class Diagram__\n

  namespace dev {
    namespace engine.image {
      class dev.engine.image.DevImageEngine {
          {static} - sImageEngine : IImageEngine
          {static} + clearDiskCache()
          {static} + clearMemoryCache()
          {static} + displayImage()
          {static} + displayImage()
          {static} + displayImage()
          {static} + displayImage()
          {static} + initEngine()
          {static} + loadImage()
          {static} + loadImage()
          - DevImageEngine()
      }
    }
  }
  

  namespace dev {
    namespace engine.image {
      interface dev.engine.image.IImageEngine {
          {abstract} + clearDiskCache()
          {abstract} + clearMemoryCache()
          {abstract} + displayImage()
          {abstract} + displayImage()
          {abstract} + displayImage()
          {abstract} + displayImage()
          {abstract} + loadImage()
          {abstract} + loadImage()
      }
    }
  }
  

  namespace dev {
    namespace engine.image {
      abstract class dev.engine.image.IImageEngine.BitmapCallBack {
          + getTranscodeType()
          {abstract} + onFailure()
          {abstract} + onResponse()
      }
    }
  }
  

  namespace dev {
    namespace engine.image {
      abstract class dev.engine.image.IImageEngine.DrawableCallBack {
          + getTranscodeType()
          {abstract} + onFailure()
          {abstract} + onResponse()
      }
    }
  }
  

  namespace dev {
    namespace engine.image {
      interface dev.engine.image.IImageEngine.ImageCallBack {
          {abstract} + getTranscodeType()
          {abstract} + onFailure()
          {abstract} + onResponse()
      }
    }
  }
  

  namespace dev {
    namespace engine.image {
      class dev.engine.image.IImageEngine.ImageConfig {
      }
    }
  }
  

  dev.engine.image.IImageEngine +-down- dev.engine.image.IImageEngine.BitmapCallBack
  dev.engine.image.IImageEngine +-down- dev.engine.image.IImageEngine.DrawableCallBack
  dev.engine.image.IImageEngine +-down- dev.engine.image.IImageEngine.ImageCallBack
  dev.engine.image.IImageEngine +-down- dev.engine.image.IImageEngine.ImageConfig
  dev.engine.image.IImageEngine.BitmapCallBack .up.|> dev.engine.image.IImageEngine.ImageCallBack
  dev.engine.image.IImageEngine.DrawableCallBack .up.|> dev.engine.image.IImageEngine.ImageCallBack


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
