@startuml

title __UTILS's Class Diagram__\n

  namespace dev {
    namespace utils {
      class dev.utils.JCLogUtils {
          {static} + DEBUG : int
          {static} + ERROR : int
          {static} + INFO : int
          {static} - DEFAULT_TAG : String
          {static} - JUDGE_CONTROL_PRINT_LOG : boolean
          {static} - JUDGE_PRINT_LOG : boolean
          {static} - sPrint : Print
          {static} + d()
          {static} + dTag()
          {static} + e()
          {static} + e()
          {static} + e()
          {static} + eTag()
          {static} + eTag()
          {static} + eTag()
          {static} + i()
          {static} + iTag()
          {static} + isPrintLog()
          {static} + setControlPrintLog()
          {static} + setPrint()
          {static} + setPrintLog()
          {static} + xml()
          {static} + xmlTag()
          - JCLogUtils()
          {static} - createMessage()
          {static} - isEmpty()
          {static} - printLog()
          {static} - splitErrorMessage()
      }
    }
  }
  

  namespace dev {
    namespace utils {
      interface dev.utils.JCLogUtils.Print {
          {abstract} + printLog()
      }
    }
  }
  

  namespace dev {
    namespace utils {
      class dev.utils.LogPrintUtils {
          {static} - DEFAULT_TAG : String
          {static} - JSON_INDENT : int
          {static} - JUDGE_PRINT_LOG : boolean
          {static} - sPrint : Print
          {static} + d()
          {static} + dTag()
          {static} + e()
          {static} + e()
          {static} + e()
          {static} + eTag()
          {static} + eTag()
          {static} + eTag()
          {static} + i()
          {static} + iTag()
          {static} + isPrintLog()
          {static} + json()
          {static} + jsonTag()
          {static} + setPrint()
          {static} + setPrintLog()
          {static} + v()
          {static} + vTag()
          {static} + w()
          {static} + wTag()
          {static} + wtf()
          {static} + wtfTag()
          {static} + xml()
          {static} + xmlTag()
          - LogPrintUtils()
          {static} - createMessage()
          {static} - isEmpty()
          {static} - printLog()
          {static} - splitErrorMessage()
      }
    }
  }
  

  namespace dev {
    namespace utils {
      interface dev.utils.LogPrintUtils.Print {
          {abstract} + printLog()
      }
    }
  }
  

  dev.utils.JCLogUtils +-down- dev.utils.JCLogUtils.Print
  dev.utils.LogPrintUtils +-down- dev.utils.LogPrintUtils.Print


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
