@startuml

title __BASE's Class Diagram__\n

  namespace dev {
    namespace base {
      class dev.base.DevBaseEntry {
          + DevBaseEntry()
          + DevBaseEntry()
          + DevBaseEntry()
          + getEntryKey()
          + getEntryValue()
          + isCorrect()
          + setEntryKey()
          + setEntryValue()
      }
    }
  }
  

  namespace dev {
    namespace base {
      class dev.base.DevBaseEvent {
          - mCode : int
          - mCodeStr : String
          - mObject : Object
          + equalsCode()
          + equalsCode()
          + equalsObject()
          + equalsValue()
          + getCode()
          + getCodeStr()
          + getObject()
          + getValue()
          + setCode()
          + setCodeStr()
          + setObject()
          + setValue()
      }
    }
  }
  

  namespace dev {
    namespace base {
      abstract class dev.base.DevBaseModel {
          - mModelId : int
          - mUUID : int
          {static} - serialVersionUID : long
          + getModelId()
          + getUuid()
          {static} + isCorrect()
          + setModelId()
          {abstract} # isCorrect()
      }
    }
  }
  

  namespace dev {
    namespace base {
      class dev.base.DevBaseVariable {
          - mLinkedHashMap : LinkedHashMap<K, V>
          + clearVariables()
          + getVariableKey()
          + getVariableKeys()
          + getVariableKeysToReverse()
          + getVariableValue()
          + getVariableValueConvert()
          + getVariableValues()
          + getVariableValuesToReverse()
          + getVariables()
          + getVariablesSize()
          + isVariable()
          + isVariable()
          + isVariableValue()
          + isVariables()
          + putVariable()
          + putVariable()
          + putVariables()
          + removeVariable()
          + removeVariableValue()
          + removeVariableValueAll()
          + toggle()
      }
    }
  }
  

  dev.base.DevBaseEntry -up-|> dev.base.DevBaseModel
  dev.base.DevBaseEntry o-- K : mEntryKey
  dev.base.DevBaseEntry o-- V : mEntryValue
  dev.base.DevBaseEvent o-- T : mValue
  dev.base.DevBaseModel .up.|> java.io.Serializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
