@startuml

title __ANIM's Class Diagram__\n

  namespace dev {
    namespace utils {
      namespace app {
        namespace anim {
          class dev.utils.app.anim.AnimationUtils {
              {static} + DEFAULT_ANIMATION_DURATION : long
              {static} - TAG : String
              {static} + cancel()
              {static} + clearAnimation()
              {static} + getAlphaAnimation()
              {static} + getAlphaAnimation()
              {static} + getAlphaAnimation()
              {static} + getAlphaAnimation()
              {static} + getAmplificationAnimation()
              {static} + getAmplificationAnimation()
              {static} + getAmplificationAnimation()
              {static} + getAnimation()
              {static} + getHiddenAlphaAnimation()
              {static} + getHiddenAlphaAnimation()
              {static} + getHiddenAlphaAnimation()
              {static} + getHiddenAlphaAnimation()
              {static} + getLessenScaleAnimation()
              {static} + getLessenScaleAnimation()
              {static} + getLessenScaleAnimation()
              {static} + getRotateAnimation()
              {static} + getRotateAnimation()
              {static} + getRotateAnimation()
              {static} + getRotateAnimationByCenter()
              {static} + getRotateAnimationByCenter()
              {static} + getRotateAnimationByCenter()
              {static} + getRotateAnimationByCenter()
              {static} + getScaleAnimation()
              {static} + getScaleAnimation()
              {static} + getScaleAnimation()
              {static} + getScaleAnimationCenter()
              {static} + getScaleAnimationCenter()
              {static} + getScaleAnimationCenter()
              {static} + getScaleAnimationCenter()
              {static} + getScaleAnimationCenter()
              {static} + getScaleAnimationCenter()
              {static} + getShakeAnimation()
              {static} + getShakeAnimation()
              {static} + getShakeAnimation()
              {static} + getShakeAnimation()
              {static} + getShakeAnimation()
              {static} + getShowAlphaAnimation()
              {static} + getShowAlphaAnimation()
              {static} + getShowAlphaAnimation()
              {static} + getShowAlphaAnimation()
              {static} + getTranslateAnimation()
              {static} + getTranslateAnimation()
              {static} + setAnimRepeat()
              {static} + setAnimation()
              {static} + setAnimationListener()
              {static} + startAnimation()
              {static} + startAnimation()
              - AnimationUtils()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace anim {
          class dev.utils.app.anim.ViewAnimationUtils {
              {static} + goneViewByAlpha()
              {static} + goneViewByAlpha()
              {static} + goneViewByAlpha()
              {static} + goneViewByAlpha()
              {static} + goneViewByAlpha()
              {static} + goneViewByAlpha()
              {static} + goneViewByAlpha()
              {static} + goneViewByAlpha()
              {static} + invisibleViewByAlpha()
              {static} + invisibleViewByAlpha()
              {static} + invisibleViewByAlpha()
              {static} + invisibleViewByAlpha()
              {static} + invisibleViewByAlpha()
              {static} + invisibleViewByAlpha()
              {static} + invisibleViewByAlpha()
              {static} + invisibleViewByAlpha()
              {static} + shake()
              {static} + shake()
              {static} + shake()
              {static} + shake()
              {static} + shake()
              {static} + shake()
              {static} + shake()
              {static} + shake()
              {static} + shake()
              {static} + shake()
              {static} + translate()
              {static} + translate()
              {static} + translate()
              {static} + visibleViewByAlpha()
              {static} + visibleViewByAlpha()
              {static} + visibleViewByAlpha()
              {static} + visibleViewByAlpha()
              {static} + visibleViewByAlpha()
              {static} + visibleViewByAlpha()
              {static} + visibleViewByAlpha()
              {static} + visibleViewByAlpha()
              - ViewAnimationUtils()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
