@startuml

title __LOGGER's Class Diagram__\n

  namespace utils_use.logger {
    class utils_use.logger.LogTools {
        {static} + getScatteredData()
        {static} + getShareMsgVoData()
        {static} + getUserInfoVoData()
    }
  }
  

  namespace utils_use.logger {
    class utils_use.logger.LoggerUse {
        {static} - LOG_TAG : String
        {static} + loggerUse()
        {static} + tempLog()
        {static} + testTime()
        - LoggerUse()
        - logConfig()
    }
  }
  

  namespace utils_use.logger {
    class utils_use.logger.TestData {
        {static} + JSON_WITH_LINE_BREAK : String
        {static} + JSON_WITH_NO_LINE_BREAK : String
        {static} + SMALL_SON_WITH_NO_LINE_BREAK : String
        {static} + XML_DATA : String
    }
  }
  

  namespace utils_use.logger {
    class utils_use.logger.TestData.ShareMsgVo {
        + sComment : String
        + sImagePath : String
        + sImageUrl : String
        + sMode : int
        + sPlatform : int
        + sSite : String
        + sSiteUrl : String
        + sTaskId : int
        + sText : String
        + sTitle : String
        + sTitleUrl : String
        + sUrl : String
        + weChatATShareType : int
    }
  }
  

  namespace utils_use.logger {
    class utils_use.logger.TestData.UserInfoVo {
        + uAge : int
        + uName : String
        + uPwd : String
    }
  }
  

  utils_use.logger.TestData +-down- utils_use.logger.TestData.ShareMsgVo
  utils_use.logger.TestData +-down- utils_use.logger.TestData.UserInfoVo


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
