@startuml

title __SERVICE's Class Diagram__\n

  namespace afkt.accessibility {
    namespace service {
      class afkt.accessibility.service.AccessibilityListenerService {
          {static} + COMMAND : String
          {static} + COMMAND_CLOSE : String
          {static} + COMMAND_OPEN : String
          {static} - TAG : String
          {static} - sListener : AccessibilityListener
          {static} - sSelf : AccessibilityListenerService
          {static} + checkAccessibility()
          {static} + checkAccessibility()
          {static} + getSelf()
          {static} + isAccessibilitySettingsOn()
          + onAccessibilityEvent()
          + onCreate()
          + onDestroy()
          + onInterrupt()
          + onStartCommand()
          {static} + setAccessibilityListener()
          {static} + startService()
          {static} + stopService()
          # onServiceConnected()
          - initTrackerWindowManager()
      }
    }
  }
  

  namespace afkt.accessibility {
    namespace service {
      abstract class afkt.accessibility.service.AccessibilityListenerService.AccessibilityListener {
          {abstract} + onAccessibilityEvent()
          + onInterrupt()
          + onServiceCreated()
          + onServiceDestroy()
      }
    }
  }
  

  afkt.accessibility.service.AccessibilityListenerService -up-|> android.accessibilityservice.AccessibilityService
  afkt.accessibility.service.AccessibilityListenerService o-- afkt.accessibility.service.TrackerWindowManager : mTrackerWindowManager
  afkt.accessibility.service.AccessibilityListenerService +-down- afkt.accessibility.service.AccessibilityListenerService.AccessibilityListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
