@startuml

title __ACTIVITY's Class Diagram__\n

  namespace dev.base {
    namespace activity {
      abstract class dev.base.activity.AbstractbsDevBaseActivity {
          # mActivity : Activity
          # mContentView : View
          # mContext : Context
          # mDialog : Dialog
          # mDialogFragment : DialogFragment
          # mIsActivityVisible : boolean
          # mPopupWindow : PopupWindow
          # mTag : String
          {abstract} + contentId()
          {abstract} + contentView()
          + getContentView()
          + getDialog()
          + getDialogFragment()
          + getPopupWindow()
          + initListeners()
          + initMethodOrder()
          + initOtherOperate()
          + initValues()
          + initViews()
          + onBackPressed()
          + setDialog()
          + setDialog()
          + setDialogFragment()
          + setDialogFragment()
          + setPopupWindow()
          + setPopupWindow()
          + showToast()
          + showToast()
          # isActivityVisible()
          # onCreate()
          # onDestroy()
          # onPause()
          # onRestart()
          # onResume()
          # onStart()
          # onStop()
          - layoutInit()
          - printLogPri()
          - printLogPri()
      }
    }
  }
  

  namespace dev.base {
    namespace activity {
      abstract class dev.base.activity.DevBaseActivity {
          + onClick()
      }
    }
  }
  

  dev.base.activity.AbstractbsDevBaseActivity .up.|> dev.base.able.IDevBaseMethod
  dev.base.activity.AbstractbsDevBaseActivity .up.|> dev.base.able.IDevBaseUIOperation
  dev.base.activity.AbstractbsDevBaseActivity .up.|> dev.base.able.IDevBaseViewOperation
  dev.base.activity.AbstractbsDevBaseActivity -up-|> androidx.appcompat.app.AppCompatActivity
  dev.base.activity.DevBaseActivity .up.|> android.view.View.OnClickListener
  dev.base.activity.DevBaseActivity -up-|> dev.base.activity.AbstractbsDevBaseActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
