@startuml

title __BEAN's Class Diagram__\n

  namespace afkt.project {
    namespace model.bean {
      class afkt.project.model.bean.ACVFileBean {
          + acvName : String
          + acvPath : String
          + ACVFileBean()
      }
    }
  }
  

  namespace afkt.project {
    namespace model.bean {
      class afkt.project.model.bean.AdapterBean {
          + content : String
          + title : String
          {static} + newAdapterBeanList()
          {static} - newAdapterBean()
      }
    }
  }
  

  namespace afkt.project {
    namespace model.bean {
      class afkt.project.model.bean.ArticleBean {
          + errorCode : int
          + errorMsg : String
      }
    }
  }
  

  namespace afkt.project {
    namespace model.bean {
      class afkt.project.model.bean.ArticleBean.DataBean {
          + curPage : int
          + datas : List<DatasBean>
          + offset : int
          + over : boolean
          + pageCount : int
          + size : int
          + total : int
      }
    }
  }
  

  namespace afkt.project {
    namespace model.bean {
      class afkt.project.model.bean.ArticleBean.DataBean.DatasBean {
          + apkLink : String
          + audit : int
          + author : String
          + chapterId : int
          + chapterName : String
          + collect : boolean
          + courseId : int
          + desc : String
          + envelopePic : String
          + fresh : boolean
          + id : int
          + link : String
          + niceDate : String
          + niceShareDate : String
          + origin : String
          + prefix : String
          + projectLink : String
          + publishTime : long
          + selfVisible : int
          + shareDate : long
          + shareUser : String
          + superChapterId : int
          + superChapterName : String
          + title : String
          + type : int
          + userId : int
          + visible : int
          + zan : int
      }
    }
  }
  

  namespace afkt.project {
    namespace model.bean {
      class afkt.project.model.bean.CommodityEvaluateBean {
          + commodityName : String
          + commodityPicture : String
          + commodityPrice : double
          {static} + newCommodityEvaluateBean()
      }
    }
  }
  

  namespace afkt.project {
    namespace model.bean {
      class afkt.project.model.bean.ItemBean {
          + content : String
          + imageUrl : String
          + subtitle : String
          + time : long
          + timeFormat : String
          + title : String
          {static} + newItemBean()
          {static} + newItemBeanPager()
      }
    }
  }
  

  namespace afkt.project {
    namespace model.bean {
      class afkt.project.model.bean.ItemStickyBean {
          + imageUrl : String
          + time : long
          + timeFormat : String
          + timeTile : String
          + ItemStickyBean()
      }
    }
  }
  

  namespace afkt.project {
    namespace model.bean {
      class afkt.project.model.bean.UserBean {
      }
    }
  }
  

  afkt.project.model.bean.ArticleBean o-- afkt.project.model.bean.ArticleBean.DataBean : data
  afkt.project.model.bean.ArticleBean +-down- afkt.project.model.bean.ArticleBean.DataBean
  afkt.project.model.bean.ArticleBean.DataBean +-down- afkt.project.model.bean.ArticleBean.DataBean.DatasBean
  afkt.project.model.bean.ItemStickyBean -up-|> afkt.project.model.bean.AdapterBean


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
