@startuml

title __ADAPTER's Class Diagram__\n

  namespace dev {
    namespace assist {
      namespace adapter {
        class dev.assist.adapter.AdapterDataAssist {
            {static} - TAG : String
            - mList : List<V>
            + AdapterDataAssist()
            + AdapterDataAssist()
            + adapterNotifyDataSetChanged()
            + addAllData()
            + addAllData()
            + addData()
            + addData()
            + clearDataList()
            + clearDataList()
            + getDataArrayList()
            + getDataCount()
            + getDataFirstItem()
            + getDataItem()
            + getDataItemPosition()
            + getDataLastItem()
            + getDataList()
            + isFirstItem()
            + isLastItem()
            + isLastItem()
            + removeData()
            + removeData()
            + removeData()
            + setAdapterNotify()
            + setDataList()
            + setDataList()
        }
      }
    }
  }
  

  namespace dev {
    namespace assist {
      namespace adapter {
        interface dev.assist.adapter.IAdapterData {
            {abstract} + addAllData()
            {abstract} + addAllData()
            {abstract} + addData()
            {abstract} + addData()
            {abstract} + clearDataList()
            {abstract} + clearDataList()
            {abstract} + getDataArrayList()
            {abstract} + getDataCount()
            {abstract} + getDataFirstItem()
            {abstract} + getDataItem()
            {abstract} + getDataItemPosition()
            {abstract} + getDataLastItem()
            {abstract} + getDataList()
            {abstract} + isFirstItem()
            {abstract} + isLastItem()
            {abstract} + isLastItem()
            {abstract} + removeData()
            {abstract} + removeData()
            {abstract} + removeData()
            {abstract} + setDataList()
            {abstract} + setDataList()
        }
      }
    }
  }
  

  namespace dev {
    namespace assist {
      namespace adapter {
        interface dev.assist.adapter.IAdapterNotify {
            {abstract} + adapterNotifyDataSetChanged()
        }
      }
    }
  }
  

  dev.assist.adapter.AdapterDataAssist .up.|> dev.assist.adapter.IAdapterData
  dev.assist.adapter.AdapterDataAssist .up.|> dev.assist.adapter.IAdapterNotify
  dev.assist.adapter.AdapterDataAssist o-- dev.assist.adapter.IAdapterNotify : mAdapterNotify


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
