@startuml

title __PANGU's Class Diagram__\n

  namespace dev.standard {
    namespace pangu {
      class dev.standard.pangu.Pangu {
          {static} - ANS_CJK : Pattern
          {static} - BRACKET_CJK : Pattern
          {static} - CJK_ANS : Pattern
          {static} - CJK_BRACKET : Pattern
          {static} - CJK_BRACKET_CJK : Pattern
          {static} - CJK_HASH : Pattern
          {static} - CJK_QUOTE : Pattern
          {static} - FIX_BRACKET : Pattern
          {static} - FIX_QUOTE : Pattern
          {static} - HASH_CJK : Pattern
          {static} - QUOTE_CJK : Pattern
          + Pangu()
          + spacingFile()
          + spacingText()
      }
    }
  }
  

  namespace dev.standard {
    namespace pangu {
      class dev.standard.pangu.PanguAnalyeMain {
          {static} - sAnnotationRepeatLineMap : HashMap<String, ArrayList<String>>
          {static} - sAnnotationSpaceMap : HashMap<String, String>
          {static} - sCoverText : boolean
          {static} - sPangu : Pangu
          {static} + main()
          {static} - createGson()
          {static} - forReader()
          {static} - getFileCatalogLists()
          {static} - readFile()
          {static} - toJsonFormat()
      }
    }
  }
  

  namespace dev.standard {
    namespace pangu {
      interface dev.standard.pangu.PanguAnalyeMain.Filter {
          {abstract} + filter()
      }
    }
  }
  

  dev.standard.pangu.PanguAnalyeMain +-down- dev.standard.pangu.PanguAnalyeMain.Filter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
