@startuml

title __RENDER's Class Diagram__\n

  namespace afkt.project {
    namespace ui {
      namespace widget {
        namespace render {
          class afkt.project.ui.widget.render.LoadingDrawable {
              - mCallback : Callback
              + LoadingDrawable()
              + draw()
              + getIntrinsicHeight()
              + getIntrinsicWidth()
              + getOpacity()
              + isRunning()
              + setAlpha()
              + setColorFilter()
              + start()
              + stop()
              # onBoundsChange()
          }
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace ui {
      namespace widget {
        namespace render {
          abstract class afkt.project.ui.widget.render.LoadingRenderer {
              # mBounds : Rect
              # mDuration : long
              # mHeight : float
              # mWidth : float
              {static} - ANIMATION_DURATION : long
              {static} - DEFAULT_SIZE : float
              - mAnimatorUpdateListener : AnimatorUpdateListener
              - mCallback : Callback
              - mRenderAnimator : ValueAnimator
              + LoadingRenderer()
              # addRenderListener()
              {abstract} # computeRender()
              # draw()
              # draw()
              {abstract} # reset()
              {abstract} # setAlpha()
              {abstract} # setColorFilter()
              ~ isRunning()
              ~ setBounds()
              ~ setCallback()
              ~ start()
              ~ stop()
              - initParams()
              - invalidateSelf()
              - setupAnimators()
          }
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace ui {
      namespace widget {
        namespace render {
          class afkt.project.ui.widget.render.LoadingRendererFactory {
              {static} - LOADING_RENDERERS : SparseArray<Class<? extends LoadingRenderer>>
              {static} + createLoadingRenderer()
              - LoadingRendererFactory()
          }
        }
      }
    }
  }
  

  afkt.project.ui.widget.render.LoadingDrawable .up.|> android.graphics.drawable.Animatable
  afkt.project.ui.widget.render.LoadingDrawable -up-|> android.graphics.drawable.Drawable
  afkt.project.ui.widget.render.LoadingDrawable o-- afkt.project.ui.widget.render.LoadingRenderer : mLoadingRender


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
