@startuml

title __CATALOG's Class Diagram__\n

  namespace dev.standard {
    namespace catalog {
      class dev.standard.catalog.CatalogGenerate {
          {static} - sMaxLength : int
          {static} + generate()
          - CatalogGenerate()
          {static} - calculateMaxLength()
          {static} - createCataLogLine()
          {static} - createCatelog()
          {static} - forCatelog()
          {static} - getFolderLists()
          {static} - getFolderLists()
      }
    }
  }
  

  namespace dev.standard {
    namespace catalog {
      interface dev.standard.catalog.CatalogGenerate.CatalogCallback {
          {abstract} + callback()
      }
    }
  }
  

  namespace dev.standard {
    namespace catalog {
      class dev.standard.catalog.CatalogMain {
          {static} - FORMAT : String
          {static} + main()
          {static} - print()
      }
    }
  }
  

  namespace dev.standard {
    namespace catalog {
      class dev.standard.catalog.Config {
          {static} + ANDROID_DIR_NAME : String
          {static} + ANDROID_LOCAL_PATH : String
          {static} + DEV_UTILS_DIR_NAME : String
          {static} + DEV_UTILS_LOCAL_PATH : String
          {static} + DIR : String
          {static} + JAVA_DIR_NAME : String
          {static} + JAVA_LOCAL_PATH : String
          {static} + USER_DIR : String
          {static} + sAndroidCatelogMap : HashMap<String, String>
          {static} + sDevUtilsCatelogMap : HashMap<String, String>
          {static} + sDevUtilsIgnoreCatelogs : List<String>
          {static} + sJavaCatelogMap : HashMap<String, String>
          - Config()
      }
    }
  }
  

  dev.standard.catalog.CatalogGenerate +-down- dev.standard.catalog.CatalogGenerate.CatalogCallback


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
