@startuml

title __COMPILER's Class Diagram__\n

  namespace dev.environment.compiler {
    class dev.environment.compiler.DevEnvironmentCompilerDebug {
        + getSupportedAnnotationTypes()
        + getSupportedSourceVersion()
        + process()
    }
  }
  

  namespace dev.environment.compiler {
    class dev.environment.compiler.Utils {
        {static} ~ ENVIRONMENT_FILE_NAME : String
        {static} ~ METHOD_ADD_ONENVIRONMENT_CHANGE_LISTENER : String
        {static} ~ METHOD_CLEAR_ONENVIRONMENT_CHANGE_LISTENER : String
        {static} ~ METHOD_DELETE_STORAGE_DIR : String
        {static} ~ METHOD_GET_ENVIRONMENTS_VALUE : String
        {static} ~ METHOD_GET_MODULE_ENVIRONMENTS_LIST : String
        {static} ~ METHOD_GET_MODULE_LIST : String
        {static} ~ METHOD_GET_STORAGE_DIR : String
        {static} ~ METHOD_IS_RELEASE : String
        {static} ~ METHOD_NOTIFY_ONENVIRONMENT_CHANGE_LISTENER : String
        {static} ~ METHOD_ONENVIRONMENT_CHANGED : String
        {static} ~ METHOD_READ_STORAGE : String
        {static} ~ METHOD_REMOVE_ONENVIRONMENT_CHANGE_LISTENER : String
        {static} ~ METHOD_RESET : String
        {static} ~ METHOD_WRITE_STORAGE : String
        {static} ~ PACKAGE_NAME : String
        {static} ~ STR_ENVIRONMENT : String
        {static} ~ STR_ENVIRONMENT_VALUE : String
        {static} ~ STR_MODULE : String
        {static} ~ STR_RELEASE_ENVIRONMENT : String
        {static} ~ TYPE_NAME_CONTEXT : TypeName
        {static} ~ TYPE_NAME_JSONOBJECT : TypeName
        {static} ~ VAR_ALIAS : String
        {static} ~ VAR_CONTEXT : String
        {static} ~ VAR_ENVIRONMENT : String
        {static} ~ VAR_ENVIRONMENT_PREFIX : String
        {static} ~ VAR_LISTENER : String
        {static} ~ VAR_LISTENER_LIST : String
        {static} ~ VAR_MODULE : String
        {static} ~ VAR_MODULELIST : String
        {static} ~ VAR_MODULE_LIST : String
        {static} ~ VAR_MODULE_NAME : String
        {static} ~ VAR_MODULE_PREFIX : String
        {static} ~ VAR_NAME : String
        {static} ~ VAR_NEW_ENVIRONMENT : String
        {static} ~ VAR_OLD_ENVIRONMENT : String
        {static} ~ VAR_SELECT_ENVIRONMENT : String
        {static} ~ VAR_VALUE : String
        {static} ~ sModuleNameMap : LinkedHashMap<String, List<String>>
        {static} + builderDevEnvironment_Class()
        {static} + builderEnvironmentChangeListener()
        {static} + builderGetMethod()
        {static} + builderIsReleaseMethod()
        {static} + builderModuleEnvironment_DATA()
        {static} + builderModuleEnvironment_DATA_NON_RELEASE()
        {static} + builderModule_DATA()
        {static} + builderResetMethod()
        {static} + builderStaticInit()
        {static} + builderStorageMethod()
        {static} + createDevEnvironmentJavaFile()
        {static} - _getEnvironmentVarName_UpperCase()
        {static} - _getListType()
        {static} - _getModuleReleaseEnvironment()
        {static} - _getModuleVarName_UpperCase()
    }
  }
  

  dev.environment.compiler.DevEnvironmentCompilerDebug -up-|> javax.annotation.processing.AbstractProcessor


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
