@startuml

title __ASSIST's Class Diagram__\n

  namespace dev.utils {
    namespace common {
      namespace assist {
        class dev.utils.common.assist.Averager {
            - mNumLists : List<Number>
            + add()
            + clear()
            + getAverage()
            + print()
            + size()
        }
      }
    }
  }
  

  namespace dev.utils {
    namespace common {
      namespace assist {
        class dev.utils.common.assist.TimeAverager {
            + average()
            + clear()
            + end()
            + endAndRestart()
            + print()
            + start()
        }
      }
    }
  }
  

  namespace dev.utils {
    namespace common {
      namespace assist {
        class dev.utils.common.assist.TimeCounter {
            - mStart : long
            + TimeCounter()
            + TimeCounter()
            + duration()
            + durationRestart()
            + getStartTime()
            + start()
        }
      }
    }
  }
  

  namespace dev.utils {
    namespace common {
      namespace assist {
        class dev.utils.common.assist.TimeKeeper {
            + waitForEnd()
            + waitForEndAsyn()
        }
      }
    }
  }
  

  namespace dev.utils {
    namespace common {
      namespace assist {
        interface dev.utils.common.assist.TimeKeeper.OnEndCallback {
            {abstract} + onEnd()
        }
      }
    }
  }
  

  dev.utils.common.assist.TimeAverager o-- dev.utils.common.assist.Averager : mAverager
  dev.utils.common.assist.TimeAverager o-- dev.utils.common.assist.TimeCounter : mTimeCounter
  dev.utils.common.assist.TimeKeeper +-down- dev.utils.common.assist.TimeKeeper.OnEndCallback


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
