@startuml

title __ENVIRONMENT's Class Diagram__\n

  namespace dev.environment {
    class dev.environment.AdapterItem {
        {static} + ENVIRONMENT_TYPE : int
        {static} + MODULE_TYPE : int
        + itemType : int
        - hashCodeEquals : int
        {static} - sModuleHashCodeMap : HashMap<String, Integer>
        + AdapterItem()
        + AdapterItem()
        {static} + changeHashCode()
        {static} + getAdapterItems()
        + isSelect()
        {static} + refreshHashCode()
    }
  }
  

  namespace dev.environment {
    class dev.environment.DevEnvironmentActivity {
        {static} + start()
        {static} + start()
        # onCreate()
    }
  }
  

  namespace dev.environment {
    class dev.environment.DevEnvironmentActivity.Adapter {
        ~ lists : List<AdapterItem>
        + Adapter()
        + getCount()
        + getItem()
        + getItemId()
        + getView()
    }
  }
  

  namespace dev.environment {
    interface dev.environment.RestartCallBack {
        {abstract} + onRestart()
    }
  }
  

  namespace dev.environment {
    class dev.environment.Utils {
        {static} # sRestartCallBack : RestartCallBack
        {static} ~ ENVIRONMENT_FILE_NAME : String
        {static} ~ METHOD_GET_MODULE_LIST : String
        {static} ~ METHOD_IS_RELEASE : String
        {static} ~ PACKAGE_NAME : String
        {static} ~ STR_ENVIRONMENT : String
        {static} ~ devEnvironmentClass : Class<?>
        {static} + getModuleEnvironment()
        {static} + getModuleList()
        {static} + isRelease()
        {static} + setModuleEnvironment()
        {static} + start()
        {static} + start()
    }
  }
  

  dev.environment.AdapterItem o-- dev.environment.bean.EnvironmentBean : environmentBean
  dev.environment.AdapterItem o-- dev.environment.bean.ModuleBean : moduleBean
  dev.environment.DevEnvironmentActivity -up-|> android.app.Activity
  dev.environment.DevEnvironmentActivity +-down- dev.environment.DevEnvironmentActivity.Adapter
  dev.environment.DevEnvironmentActivity.Adapter -up-|> android.widget.BaseAdapter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
