@startuml

title __MVP's Class Diagram__\n

  namespace afkt.project {
    namespace framework.mvp {
      class afkt.project.framework.mvp.ArticleMVP {
      }
    }
  }
  

  namespace afkt.project {
    namespace framework.mvp {
      interface afkt.project.framework.mvp.ArticleMVP.IPresenter {
          {abstract} + getArticleLists()
      }
    }
  }
  

  namespace afkt.project {
    namespace framework.mvp {
      interface afkt.project.framework.mvp.ArticleMVP.Model {
          {abstract} + requestArticleLists()
      }
    }
  }
  

  namespace afkt.project {
    namespace framework.mvp {
      class afkt.project.framework.mvp.ArticleMVP.Presenter {
          + Presenter()
          + getArticleLists()
      }
    }
  }
  

  namespace afkt.project {
    namespace framework.mvp {
      interface afkt.project.framework.mvp.ArticleMVP.View {
          {abstract} + addDisposable()
          {abstract} + onArticleListResponse()
      }
    }
  }
  

  namespace afkt.project {
    namespace framework.mvp {
      class afkt.project.framework.mvp.ArticleMVPActivity {
          ~ vid_bvr_recy : RecyclerView
          ~ vid_sli_load_view : WhorlView
          + addDisposable()
          + getLayoutId()
          + initListeners()
          + initOtherOperate()
          + initValues()
          + initViews()
          + onArticleListResponse()
          # onDestroy()
          # presenter()
      }
    }
  }
  

  afkt.project.framework.mvp.ArticleMVP +-down- afkt.project.framework.mvp.ArticleMVP.IPresenter
  afkt.project.framework.mvp.ArticleMVP +-down- afkt.project.framework.mvp.ArticleMVP.Model
  afkt.project.framework.mvp.ArticleMVP +-down- afkt.project.framework.mvp.ArticleMVP.Presenter
  afkt.project.framework.mvp.ArticleMVP +-down- afkt.project.framework.mvp.ArticleMVP.View
  afkt.project.framework.mvp.ArticleMVP.Presenter .up.|> afkt.project.framework.mvp.ArticleMVP.IPresenter
  afkt.project.framework.mvp.ArticleMVP.Presenter -up-|> dev.base.mvp.MVP.Presenter
  afkt.project.framework.mvp.ArticleMVPActivity .up.|> afkt.project.framework.mvp.ArticleMVP.View
  afkt.project.framework.mvp.ArticleMVPActivity -up-|> afkt.project.base.app.BaseMVPToolbarActivity
  afkt.project.framework.mvp.ArticleMVPActivity o-- afkt.project.ui.adapter.ArticleAdapter : articleAdapter


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
