@startuml

title __HTTP's Class Diagram__\n

  namespace afkt.project {
    namespace base.constants {
      namespace http {
        class afkt.project.base.constants.http.HttpApis {
            {static} + getArticleListUrl()
            - HttpApis()
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace base.constants {
      namespace http {
        class afkt.project.base.constants.http.HttpConstants {
            - HttpConstants()
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace base.constants {
      namespace http {
        class afkt.project.base.constants.http.HttpConstants.IM {
            - debug : String
            - release : String
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace base.constants {
      namespace http {
        class afkt.project.base.constants.http.HttpConstants.Map {
            - baidu : String
            - gaode : String
            - google : String
            - qq : String
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace base.constants {
      namespace http {
        class afkt.project.base.constants.http.HttpConstants.Service {
            - debug : String
            - development : String
            - pre_release : String
            - release : String
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace base.constants {
      namespace http {
        class afkt.project.base.constants.http.HttpConstants.Switch {
            - close : String
            - open : String
        }
      }
    }
  }
  

  afkt.project.base.constants.http.HttpConstants +-down- afkt.project.base.constants.http.HttpConstants.IM
  afkt.project.base.constants.http.HttpConstants +-down- afkt.project.base.constants.http.HttpConstants.Map
  afkt.project.base.constants.http.HttpConstants +-down- afkt.project.base.constants.http.HttpConstants.Service
  afkt.project.base.constants.http.HttpConstants +-down- afkt.project.base.constants.http.HttpConstants.Switch


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
