@startuml

title __PERMISSION's Class Diagram__\n

  namespace dev {
    namespace utils {
      namespace app {
        namespace permission {
          class dev.utils.app.permission.PermissionConstants {
              {static} + CALENDAR : String
              {static} + CALL_LOG : String
              {static} + CAMERA : String
              {static} + CONTACTS : String
              {static} + LOCATION : String
              {static} + MICROPHONE : String
              {static} + PHONE : String
              {static} + SENSORS : String
              {static} + SMS : String
              {static} + STORAGE : String
              {static} - GROUP_CALENDAR : String[]
              {static} - GROUP_CALL_LOG : String[]
              {static} - GROUP_CAMERA : String[]
              {static} - GROUP_CONTACTS : String[]
              {static} - GROUP_LOCATION : String[]
              {static} - GROUP_MICROPHONE : String[]
              {static} - GROUP_PHONE : String[]
              {static} - GROUP_PHONE_BELOW_O : String[]
              {static} - GROUP_SENSORS : String[]
              {static} - GROUP_SMS : String[]
              {static} - GROUP_STORAGE : String[]
              {static} + getPermissions()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace permission {
          interface dev.utils.app.permission.PermissionConstants.Permission {
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace permission {
          class dev.utils.app.permission.PermissionUtils {
              {static} + P_REQUEST_CODE : int
              {static} - TAG : String
              - mHandler : Handler
              - mIsRequest : boolean
              - mIsRequestPermissionsResult : boolean
              - mPermissionSets : Set<String>
              - mPermissionsDeniedLists : List<String>
              - mPermissionsGrantedLists : List<String>
              - mPermissionsNotFoundLists : List<String>
              - mPermissionsRequestLists : List<String>
              {static} - sAppPermissionSets : Set<String>
              {static} - sInstance : PermissionUtils
              {static} - sPermissionsDeniedForeverLists : List<String>
              {static} + againRequest()
              + callBack()
              {static} + canRequestPackageInstalls()
              {static} + getAllPermissionToList()
              {static} + getAllPermissionToSet()
              {static} + getAppPermission()
              {static} + getAppPermission()
              {static} + getAppPermissionToList()
              {static} + getAppPermissionToSet()
              {static} + getDeniedPermissionStatus()
              {static} + isGranted()
              {static} + notifyPermissionsChange()
              {static} + onRequestPermissionsResult()
              {static} + permission()
              + request()
              + request()
              + setRequestPermissionsResult()
              {static} + shouldShowRequestPermissionRationale()
              - PermissionUtils()
              - checkPermissions()
              - getPermissionsStatus()
              {static} - isGranted()
              - onRequestPermissionsResultCommon()
              - requestCallback()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace permission {
          class dev.utils.app.permission.PermissionUtils.PermissionActivity {
              + onRequestPermissionsResult()
              # onCreate()
              {static} # start()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace permission {
          interface dev.utils.app.permission.PermissionUtils.PermissionCallBack {
              {abstract} + onDenied()
              {abstract} + onGranted()
          }
        }
      }
    }
  }
  

  dev.utils.app.permission.PermissionConstants +-down- dev.utils.app.permission.PermissionConstants.Permission
  dev.utils.app.permission.PermissionUtils o-- dev.utils.app.permission.PermissionUtils.PermissionCallBack : mCallBack
  dev.utils.app.permission.PermissionUtils +-down- dev.utils.app.permission.PermissionUtils.PermissionActivity
  dev.utils.app.permission.PermissionUtils +-down- dev.utils.app.permission.PermissionUtils.PermissionCallBack
  dev.utils.app.permission.PermissionUtils.PermissionActivity -up-|> android.app.Activity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
