@startuml

title __SERVICE's Class Diagram__\n

  namespace dev.service {
    class dev.service.AccessibilityListenerService {
        {static} - TAG : String
        {static} - sListener : AccessibilityListener
        {static} - sSelf : AccessibilityListenerService
        {static} + checkAccessibility()
        {static} + checkAccessibility()
        {static} + getSelf()
        {static} + isAccessibilitySettingsOn()
        + onAccessibilityEvent()
        + onCreate()
        + onDestroy()
        + onInterrupt()
        {static} + setAccessibilityListener()
        {static} + startService()
        {static} + stopService()
        # onServiceConnected()
    }
  }
  

  namespace dev.service {
    abstract class dev.service.AccessibilityListenerService.AccessibilityListener {
        {abstract} + onAccessibilityEvent()
        + onInterrupt()
        + onServiceCreated()
        + onServiceDestroy()
    }
  }
  

  namespace dev.service {
    class dev.service.NotificationService {
        {static} - TAG : String
        {static} - sListener : NotificationListener
        {static} - sSelf : NotificationService
        + cancelNotification()
        {static} + checkAndIntentSetting()
        {static} + getSelf()
        {static} + isNotificationListenerEnabled()
        {static} + isNotificationListenerEnabled()
        + onCreate()
        + onDestroy()
        + onNotificationPosted()
        + onNotificationRemoved()
        + onStartCommand()
        {static} + setNotificationListener()
        {static} + startNotificationListenSettings()
        {static} + startService()
        {static} + stopService()
    }
  }
  

  namespace dev.service {
    interface dev.service.NotificationService.NotificationListener {
        {abstract} + onNotificationPosted()
        {abstract} + onNotificationRemoved()
        {abstract} + onServiceCreated()
        {abstract} + onServiceDestroy()
        {abstract} + onStartCommand()
    }
  }
  

  dev.service.AccessibilityListenerService -up-|> android.accessibilityservice.AccessibilityService
  dev.service.AccessibilityListenerService +-down- dev.service.AccessibilityListenerService.AccessibilityListener
  dev.service.NotificationService -up-|> android.service.notification.NotificationListenerService
  dev.service.NotificationService +-down- dev.service.NotificationService.NotificationListener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
