@startuml

title __APP's Class Diagram__\n

  namespace afkt.project {
    namespace base.app {
      abstract class afkt.project.base.app.BaseActivity {
          + unbinder : Unbinder
          # vid_ba_content_linear : LinearLayout
          # vid_ba_linear : LinearLayout
          # vid_ba_state_linear : LinearLayout
          # vid_ba_title_linear : LinearLayout
          + contentId()
          + contentView()
          {abstract} + getLayoutId()
          + insertStateLayout()
          + registerAdapterDataObserver()
          + registerAdapterDataObserver()
          + registerAdapterDataObserver()
          + showToast()
          + showToast()
          + showToast()
          # onCreate()
          # onDestroy()
          - layoutInit()
      }
    }
  }
  

  namespace afkt.project {
    namespace base.app {
      class afkt.project.base.app.BaseApplication {
          {static} + isDebug()
          + onCreate()
          - init()
          - initCrash()
          - initOthers()
          - initStateLayout()
          - initWebViewBuilder()
          - printProInfo()
      }
    }
  }
  

  namespace afkt.project {
    namespace base.app {
      abstract class afkt.project.base.app.BaseMVPActivity {
          + unbinder : Unbinder
          # vid_ba_content_linear : LinearLayout
          # vid_ba_linear : LinearLayout
          # vid_ba_state_linear : LinearLayout
          # vid_ba_title_linear : LinearLayout
          + contentId()
          + contentView()
          {abstract} + getLayoutId()
          + insertStateLayout()
          + registerAdapterDataObserver()
          + registerAdapterDataObserver()
          + registerAdapterDataObserver()
          + showToast()
          + showToast()
          + showToast()
          # onCreate()
          # onDestroy()
          - layoutInit()
      }
    }
  }
  

  namespace afkt.project {
    namespace base.app {
      abstract class afkt.project.base.app.BaseMVPToolbarActivity {
          # vid_bt_toolbar : Toolbar
          # getModuleType()
          # initToolBar()
          # onCreate()
          # setTitle()
      }
    }
  }
  

  namespace afkt.project {
    namespace base.app {
      abstract class afkt.project.base.app.BaseMVVMActivity {
          # onCreate()
          # onDestroy()
      }
    }
  }
  

  namespace afkt.project {
    namespace base.app {
      abstract class afkt.project.base.app.BaseToolbarActivity {
          # vid_bt_toolbar : Toolbar
          # getModuleType()
          # initToolBar()
          # onCreate()
          # setTitle()
      }
    }
  }
  

  afkt.project.base.app.BaseActivity -up-|> dev.base.activity.DevBaseActivity
  afkt.project.base.app.BaseActivity o-- dev.widget.function.StateLayout : stateLayout
  afkt.project.base.app.BaseApplication -up-|> androidx.multidex.MultiDexApplication
  afkt.project.base.app.BaseMVPActivity -up-|> dev.base.mvp.DevBaseMVPActivity
  afkt.project.base.app.BaseMVPActivity o-- dev.widget.function.StateLayout : stateLayout
  afkt.project.base.app.BaseMVPToolbarActivity -up-|> afkt.project.base.app.BaseMVPActivity
  afkt.project.base.app.BaseMVVMActivity -up-|> afkt.project.base.app.BaseActivity
  afkt.project.base.app.BaseMVVMActivity o-- VDB : viewDataBinding
  afkt.project.base.app.BaseToolbarActivity -up-|> afkt.project.base.app.BaseActivity


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
