@startuml

title __MANAGER's Class Diagram__\n

  namespace dev {
    namespace utils {
      namespace app {
        namespace assist {
          namespace manager {
            class dev.utils.app.assist.manager.TimerManager {
                {static} - TAG : String
                {static} - mTimerLists : List<AbsTimer>
                {static} + closeAll()
                {static} + closeInfiniteTask()
                {static} + closeMark()
                {static} + closeMark()
                {static} + closeNotRunTask()
                {static} + createTimer()
                {static} + createTimer()
                {static} + createTimer()
                {static} + createTimer()
                {static} + createTimer()
                {static} + createTimer()
                {static} + createTimer()
                {static} + gc()
                {static} + getTimer()
                {static} + getTimer()
                {static} + getTimerSize()
                {static} + getTimers()
                {static} + getTimers()
                - TimerManager()
            }
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace assist {
          namespace manager {
            abstract class dev.utils.app.assist.manager.TimerManager.AbsTimer {
                {static} + TIMER_NOTIFY_WHAT : int
                - markId : int
                - markStr : String
                - markSweep : boolean
                + closeTimer()
                + getMarkId()
                + getMarkStr()
                {abstract} + getTriggerLimit()
                {abstract} + getTriggerNumber()
                {abstract} + isInfinite()
                {abstract} + isRunTimer()
                {abstract} + isTriggerEnd()
                {abstract} + setHandler()
                + setMarkId()
                + setMarkStr()
                {abstract} + setNotifyObject()
                {abstract} + setNotifyWhat()
                {abstract} + setTime()
                {abstract} + setTriggerLimit()
                + startTimer()
            }
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace assist {
          namespace manager {
            class dev.utils.app.assist.manager.TimerManager.TimerTask {
                - delay : long
                - handler : Handler
                - notifyObj : Object
                - notifyWhat : int
                - period : long
                - running : boolean
                - timer : Timer
                - timerTask : TimerTask
                - triggerLimit : int
                - triggerNumber : int
                + TimerTask()
                + closeTimer()
                + getTriggerLimit()
                + getTriggerNumber()
                + isInfinite()
                + isRunTimer()
                + isTriggerEnd()
                + setHandler()
                + setNotifyObject()
                + setNotifyWhat()
                + setTime()
                + setTriggerLimit()
                + startTimer()
                - close()
                - start()
            }
          }
        }
      }
    }
  }
  

  dev.utils.app.assist.manager.TimerManager +-down- dev.utils.app.assist.manager.TimerManager.AbsTimer
  dev.utils.app.assist.manager.TimerManager +-down- dev.utils.app.assist.manager.TimerManager.TimerTask
  dev.utils.app.assist.manager.TimerManager.TimerTask -up-|> dev.utils.app.assist.manager.TimerManager.AbsTimer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
