@startuml

title __CONSTANTS's Class Diagram__\n

  namespace afkt.project {
    namespace base.constants {
      class afkt.project.base.constants.CallBackConstants {
          {static} + CALL_REQUEST_CODE : int
          - CallBackConstants()
      }
    }
  }
  

  namespace afkt.project {
    namespace base.constants {
      class afkt.project.base.constants.KeyConstants {
          - KeyConstants()
      }
    }
  }
  

  namespace afkt.project {
    namespace base.constants {
      class afkt.project.base.constants.KeyConstants.Common {
          {static} + KEY_DATA : String
          {static} + KEY_OBJECT : String
          {static} + KEY_PARAMS : String
          {static} + KEY_TITLE : String
          {static} + KEY_TYPE : String
          - Common()
      }
    }
  }
  

  namespace afkt.project {
    namespace base.constants {
      class afkt.project.base.constants.KeyConstants.Extra {
          {static} + KEY_DATA : String
          {static} + KEY_OBJECT : String
          {static} + KEY_PARAMS : String
          {static} + KEY_TITLE : String
          - Extra()
      }
    }
  }
  

  namespace afkt.project {
    namespace base.constants {
      class afkt.project.base.constants.KeyConstants.Other {
          {static} + KEY_DECODEMODE : String
      }
    }
  }
  

  afkt.project.base.constants.KeyConstants +-down- afkt.project.base.constants.KeyConstants.Common
  afkt.project.base.constants.KeyConstants +-down- afkt.project.base.constants.KeyConstants.Extra
  afkt.project.base.constants.KeyConstants +-down- afkt.project.base.constants.KeyConstants.Other


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
