@startuml

title __CIPHER's Class Diagram__\n

  namespace dev {
    namespace utils {
      namespace common {
        namespace cipher {
          class dev.utils.common.cipher.Base64 {
              {static} + CRLF : int
              {static} + DEFAULT : int
              {static} + NO_CLOSE : int
              {static} + NO_PADDING : int
              {static} + NO_WRAP : int
              {static} + URL_SAFE : int
              {static} + decode()
              {static} + decode()
              {static} + decode()
              {static} + encode()
              {static} + encode()
              {static} + encodeToString()
              {static} + encodeToString()
              - Base64()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace common {
        namespace cipher {
          abstract class dev.utils.common.cipher.Base64.Coder {
              + op : int
              + output : byte[]
              {abstract} + maxOutputSize()
              {abstract} + process()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace common {
        namespace cipher {
          class dev.utils.common.cipher.Base64.Decoder {
              {static} - DECODE : int[]
              {static} - DECODE_WEBSAFE : int[]
              {static} - EQUALS : int
              {static} - SKIP : int
              - alphabet : int[]
              - state : int
              - value : int
              + Decoder()
              + maxOutputSize()
              + process()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace common {
        namespace cipher {
          class dev.utils.common.cipher.Base64.Encoder {
              {static} + LINE_GROUPS : int
              + do_cr : boolean
              + do_newline : boolean
              + do_padding : boolean
              ~ tailLen : int
              {static} - ENCODE : byte[]
              {static} - ENCODE_WEBSAFE : byte[]
              - alphabet : byte[]
              - count : int
              - tail : byte[]
              + Encoder()
              + maxOutputSize()
              + process()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace common {
        namespace cipher {
          class dev.utils.common.cipher.Base64Cipher {
              - mFlags : int
              + Base64Cipher()
              + Base64Cipher()
              + Base64Cipher()
              + decrypt()
              + encrypt()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace common {
        namespace cipher {
          interface dev.utils.common.cipher.Cipher {
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace common {
        namespace cipher {
          class dev.utils.common.cipher.CipherUtils {
              {static} + decrypt()
              {static} + decrypt()
              {static} + encrypt()
              {static} + encrypt()
              - CipherUtils()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace common {
        namespace cipher {
          interface dev.utils.common.cipher.Decrypt {
              {abstract} + decrypt()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace common {
        namespace cipher {
          interface dev.utils.common.cipher.Encrypt {
              {abstract} + encrypt()
          }
        }
      }
    }
  }
  

  dev.utils.common.cipher.Base64 +-down- dev.utils.common.cipher.Base64.Coder
  dev.utils.common.cipher.Base64 +-down- dev.utils.common.cipher.Base64.Decoder
  dev.utils.common.cipher.Base64 +-down- dev.utils.common.cipher.Base64.Encoder
  dev.utils.common.cipher.Base64.Decoder -up-|> dev.utils.common.cipher.Base64.Coder
  dev.utils.common.cipher.Base64.Encoder -up-|> dev.utils.common.cipher.Base64.Coder
  dev.utils.common.cipher.Base64Cipher .up.|> dev.utils.common.cipher.Cipher
  dev.utils.common.cipher.Base64Cipher o-- dev.utils.common.cipher.Cipher : mCipher


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
