@startuml

title __UTIL's Class Diagram__\n

  namespace afkt.project {
    namespace util {
      class afkt.project.util.GPUFilterUtils {
          {static} - TAG : String
          {static} + getFilterBitmap()
          {static} + getFilterBitmap()
          {static} + getFilterBitmap()
          {static} + getGPUImageToneCurveFilter()
          - GPUFilterUtils()
      }
    }
  }
  

  namespace afkt.project {
    namespace util {
      class afkt.project.util.ProjectUtils {
          {static} - sRoundOptions : RequestOptions
          {static} + getRoundOptions()
          {static} + getRoundOptions10()
          {static} + refShape()
          - ProjectUtils()
      }
    }
  }
  

  namespace afkt.project {
    namespace util {
      class afkt.project.util.QuickWifiHotUtils {
          {static} - CHECK_HOT_CONN : int
          {static} - CLOSE_WIFI_SUCCESS : int
          {static} - START_WIFISPOT_SUCCESS : int
          - TAG : String
          - closeWifiThread : Thread
          - hotCheckThread : Thread
          - hotHandler : Handler
          - hotPwd : String
          - hotSSID : String
          - isCheck : boolean
          - isStop : boolean
          - isThreadCheckHot : boolean
          - startWifiSpotThread : Thread
          + QuickWifiHotUtils()
          + closeHotspot()
          + openHotspot()
          + setOperate()
          - setWifiApCheck()
          - setWifiCheck()
      }
    }
  }
  

  namespace afkt.project {
    namespace util {
      interface afkt.project.util.QuickWifiHotUtils.Operate {
          {abstract} + isFinishing()
      }
    }
  }
  

  namespace afkt.project {
    namespace util {
      class afkt.project.util.SkipUtils {
          {static} + startActivity()
          - SkipUtils()
      }
    }
  }
  

  namespace afkt.project {
    namespace util {
      class afkt.project.util.ViewAssistUtils {
          {static} + registerRecyclerLoading()
          - ViewAssistUtils()
      }
    }
  }
  

  afkt.project.util.QuickWifiHotUtils o-- afkt.project.util.QuickWifiHotUtils.Operate : operate
  afkt.project.util.QuickWifiHotUtils o-- dev.utils.app.wifi.WifiHotUtils : wifiHotUtils
  afkt.project.util.QuickWifiHotUtils o-- dev.utils.app.wifi.WifiUtils : wifiUtils
  afkt.project.util.QuickWifiHotUtils +-down- afkt.project.util.QuickWifiHotUtils.Operate


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
