@startuml

title __HELPER's Class Diagram__\n

  namespace dev {
    namespace utils {
      namespace app {
        namespace helper {
          class dev.utils.app.helper.DevHelper {
              {static} - HELPER : DevHelper
              + addTextChangedListener()
              + addTouchArea()
              + addTouchArea()
              + applyLanguage()
              + applyLanguage()
              + autoCloseDialog()
              + autoCloseDialog()
              + autoClosePopupWindow()
              + cancel()
              + cancelAllNotification()
              + cancelNotification()
              + cancelNotification()
              + cleanAppCache()
              + cleanAppDbByName()
              + cleanAppDbs()
              + cleanAppFiles()
              + cleanAppSp()
              + cleanAppSp()
              + cleanApplicationData()
              + cleanCache()
              + cleanCustomDir()
              + cleanCustomDir()
              + closeDialog()
              + closeDialog()
              + closeDialogs()
              + closeDialogs()
              + closeIO()
              + closeIOQuietly()
              + closeKeyBoardSpecial()
              + closeKeyBoardSpecial()
              + closeKeyBoardSpecial()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closeKeyboard()
              + closePopupWindow()
              + closePopupWindows()
              + closeTimer()
              + copyIntent()
              + copyText()
              + copyUri()
              + devHelper()
              + forceGetViewSize()
              {static} + get()
              + getNetTime()
              + getNetTime()
              + judgeView()
              + notifyMediaStore()
              + notifyMediaStore()
              + notifyNotification()
              + notifyNotification()
              + openKeyboard()
              + openKeyboard()
              + openKeyboard()
              + openKeyboard()
              + openKeyboard()
              + openKeyboard()
              + postRunnable()
              + postRunnable()
              + postRunnable()
              + postRunnable()
              + record()
              + recycle()
              + registerSoftInputChangedListener()
              + registerSoftInputChangedListener2()
              + removeRunnable()
              + removeTextChangedListener()
              + saveAssetsFormFile()
              + saveBitmapToSDCard()
              + saveBitmapToSDCard()
              + saveBitmapToSDCardJPEG()
              + saveBitmapToSDCardJPEG()
              + saveBitmapToSDCardJPEG()
              + saveBitmapToSDCardJPEG()
              + saveBitmapToSDCardPNG()
              + saveBitmapToSDCardPNG()
              + saveBitmapToSDCardPNG()
              + saveBitmapToSDCardPNG()
              + saveBitmapToSDCardWEBP()
              + saveBitmapToSDCardWEBP()
              + saveBitmapToSDCardWEBP()
              + saveBitmapToSDCardWEBP()
              + saveRawFormFile()
              + setAnimationListener()
              + setFullScreen()
              + setFullScreenNoTitle()
              + setKeyListener()
              + setKeyListener()
              + setKeyListener()
              + setLandscape()
              + setOnClicks()
              + setOnLongClicks()
              + setOnTouchs()
              + setPortrait()
              + setWindowSecure()
              + showDialog()
              + startTimer()
              + toggleScreenOrientation()
              + vibrate()
              + vibrate()
              + viewHelper()
              + waitForEnd()
              + waitForEndAsyn()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace helper {
          class dev.utils.app.helper.ViewHelper {
              {static} - HELPER : ViewHelper
              + addRule()
              + addRule()
              + addRules()
              + addRules()
              + addTextChangedListener()
              + addTouchArea()
              + addTouchArea()
              + clearAnimation()
              + clearFlags()
              + clearFocus()
              + devHelper()
              + fullScroll()
              {static} + get()
              + insert()
              + insert()
              + postRunnable()
              + postRunnable()
              + postRunnable()
              + postRunnable()
              + removeRule()
              + removeRules()
              + removeRunnable()
              + removeSelfFromParent()
              + removeTextChangedListener()
              + requestFocus()
              + requestLayout()
              + requestLayoutParent()
              + reverseVisibilitys()
              + reverseVisibilitys()
              + reverseVisibilitys()
              + reverseVisibilitys()
              + scrollBy()
              + scrollTo()
              + scrollToBottom()
              + scrollToPosition()
              + scrollToTop()
              + setAdjustViewBounds()
              + setAllCaps()
              + setAlpha()
              + setAnimation()
              + setAntiAliasFlag()
              + setAutoLinkMask()
              + setBackground()
              + setBackgroundColor()
              + setBackgroundResource()
              + setBackgroundResources()
              + setBackgroundResources()
              + setBackgroundTintList()
              + setBackgroundTintMode()
              + setBold()
              + setBold()
              + setBold()
              + setClickable()
              + setClipChildren()
              + setColorFilter()
              + setColorFilter()
              + setColorFilter()
              + setColorFilter()
              + setCompoundDrawablePadding()
              + setCompoundDrawables()
              + setCompoundDrawablesByBottom()
              + setCompoundDrawablesByLeft()
              + setCompoundDrawablesByRight()
              + setCompoundDrawablesByTop()
              + setCompoundDrawablesWithIntrinsicBounds()
              + setCompoundDrawablesWithIntrinsicBoundsByBottom()
              + setCompoundDrawablesWithIntrinsicBoundsByLeft()
              + setCompoundDrawablesWithIntrinsicBoundsByRight()
              + setCompoundDrawablesWithIntrinsicBoundsByTop()
              + setCursorVisible()
              + setDescendantFocusability()
              + setEllipsize()
              + setEms()
              + setEnabled()
              + setFocusable()
              + setFocusableInTouchMode()
              + setForeground()
              + setForegroundGravity()
              + setForegroundTintList()
              + setForegroundTintMode()
              + setHeight()
              + setHeight()
              + setHint()
              + setHintTextColor()
              + setHintTextColor()
              + setHintTextColors()
              + setHintTextColors()
              + setHorizontalScrollBarEnabled()
              + setHtmlText()
              + setHtmlTexts()
              + setImageBitmap()
              + setImageBitmaps()
              + setImageBitmaps()
              + setImageDrawable()
              + setImageDrawables()
              + setImageDrawables()
              + setImageMatrix()
              + setImageResource()
              + setImageResources()
              + setImageResources()
              + setImageTintList()
              + setImageTintMode()
              + setImeOptions()
              + setIncludeFontPadding()
              + setInputType()
              + setKeyListener()
              + setKeyListener()
              + setKeyListener()
              + setLayerType()
              + setLayoutGravity()
              + setLayoutParams()
              + setLetterSpacing()
              + setLineSpacing()
              + setLineSpacingAndMultiplier()
              + setLines()
              + setLongClickable()
              + setMargin()
              + setMargin()
              + setMargin()
              + setMargin()
              + setMargin()
              + setMargin()
              + setMarginBottom()
              + setMarginBottom()
              + setMarginLeft()
              + setMarginLeft()
              + setMarginRight()
              + setMarginRight()
              + setMarginTop()
              + setMarginTop()
              + setMaxEms()
              + setMaxHeight()
              + setMaxLength()
              + setMaxLengthAndText()
              + setMaxLines()
              + setMaxWidth()
              + setMinEms()
              + setMinLines()
              + setMinimumHeight()
              + setMinimumWidth()
              + setNextFocusDownId()
              + setNextFocusForwardId()
              + setNextFocusLeftId()
              + setNextFocusRightId()
              + setNextFocusUpId()
              + setOnClicks()
              + setOnLongClicks()
              + setOnTouchs()
              + setOverScrollMode()
              + setPadding()
              + setPadding()
              + setPadding()
              + setPadding()
              + setPadding()
              + setPadding()
              + setPaddingBottom()
              + setPaddingBottom()
              + setPaddingLeft()
              + setPaddingLeft()
              + setPaddingRight()
              + setPaddingRight()
              + setPaddingTop()
              + setPaddingTop()
              + setPaintFlags()
              + setPivotX()
              + setPivotY()
              + setRotation()
              + setRotationX()
              + setRotationY()
              + setScaleType()
              + setScaleTypes()
              + setScaleTypes()
              + setScaleX()
              + setScaleY()
              + setScrollContainer()
              + setSelected()
              + setSelection()
              + setSelectionToBottom()
              + setSelectionToTop()
              + setStrikeThruText()
              + setStrikeThruText()
              + setTag()
              + setText()
              + setText()
              + setTextAlignment()
              + setTextColor()
              + setTextColor()
              + setTextColors()
              + setTextColors()
              + setTextDirection()
              + setTextGravity()
              + setTextScaleX()
              + setTextSize()
              + setTextSizeByDp()
              + setTextSizeByIn()
              + setTextSizeByPx()
              + setTextSizeBySp()
              + setTextSizes()
              + setTexts()
              + setTransformationMethod()
              + setTransformationMethod()
              + setTransformationMethod()
              + setTranslationX()
              + setTranslationY()
              + setTypeface()
              + setUnderlineText()
              + setUnderlineText()
              + setVerticalScrollBarEnabled()
              + setVisibility()
              + setVisibility()
              + setVisibilitys()
              + setVisibilitys()
              + setWidth()
              + setWidth()
              + setWidthHeight()
              + setWidthHeight()
              + smoothScrollBy()
              + smoothScrollTo()
              + smoothScrollToBottom()
              + smoothScrollToPosition()
              + smoothScrollToTop()
              + startAnimation()
              + toggleClickable()
              + toggleEnabled()
              + toggleFocusable()
              + toggleLongClickable()
              + toggleSelected()
              + toggleVisibilitys()
              + toggleVisibilitys()
              + toggleVisibilitys()
              + viewHelper()
          }
        }
      }
    }
  }
  

  dev.utils.app.helper.DevHelper o-- dev.utils.common.assist.TimeKeeper : mTimeKeeper


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
