@startuml

title __WIDGET's Class Diagram__\n

  namespace afkt.project {
    namespace ui {
      namespace widget {
        class afkt.project.ui.widget.AutoGridView {
            {static} - TAG : String
            - numColumns : int
            - numColumnsID : int
            - previousFirstVisible : int
            + AutoGridView()
            + AutoGridView()
            + AutoGridView()
            + setNumColumns()
            # onConfigurationChanged()
            # onLayout()
            # onScrollChanged()
            - init()
            - setHeights()
            - updateColumns()
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace ui {
      namespace widget {
        class afkt.project.ui.widget.BaseButton {
            + BaseButton()
            + BaseButton()
            + BaseButton()
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace ui {
      namespace widget {
        class afkt.project.ui.widget.BaseEditText {
            + BaseEditText()
            + BaseEditText()
            + BaseEditText()
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace ui {
      namespace widget {
        class afkt.project.ui.widget.BaseImageView {
            + BaseImageView()
            + BaseImageView()
            + BaseImageView()
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace ui {
      namespace widget {
        class afkt.project.ui.widget.BaseRefreshView {
            - adapter : BaseQuickAdapter
            - body : FrameLayout
            - pageAssist : PageAssist<String>
            - recyclerView : RecyclerView
            - smartRefreshLayout : SmartRefreshLayout
            + BaseRefreshView()
            + BaseRefreshView()
            + BaseRefreshView()
            + BaseRefreshView()
            + addFooterView()
            + addFooterView()
            + addHeaderView()
            + addHeaderView()
            + finishLoadMore()
            + finishRefresh()
            + finishRefreshAndLoad()
            + finishRefreshOrLoad()
            + getAdapter()
            + getBody()
            + getFooterLayoutCount()
            + getHeaderLayoutCount()
            + getPageAssist()
            + getRecyclerView()
            + setAdapter()
            + setEnableLoadMore()
            + setEnableRefresh()
            + setLayoutManager()
            + setNoMoreData()
            + setOnLoadMoreListener()
            + setOnRefreshListener()
            + setOnRefreshLoadMoreListener()
            + setPageAssist()
            - init()
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace ui {
      namespace widget {
        class afkt.project.ui.widget.BaseTextView {
            + BaseTextView()
            + BaseTextView()
            + BaseTextView()
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace ui {
      namespace widget {
        class afkt.project.ui.widget.LoadingView {
            + LoadingView()
            + LoadingView()
            + setLoadingRenderer()
            # onAttachedToWindow()
            # onDetachedFromWindow()
            # onVisibilityChanged()
            - initAttrs()
            - startAnimation()
            - stopAnimation()
        }
      }
    }
  }
  

  afkt.project.ui.widget.AutoGridView -up-|> android.widget.GridView
  afkt.project.ui.widget.BaseButton -up-|> androidx.appcompat.widget.AppCompatButton
  afkt.project.ui.widget.BaseEditText -up-|> androidx.appcompat.widget.AppCompatEditText
  afkt.project.ui.widget.BaseImageView -up-|> androidx.appcompat.widget.AppCompatImageView
  afkt.project.ui.widget.BaseRefreshView -up-|> android.widget.LinearLayout
  afkt.project.ui.widget.BaseTextView -up-|> androidx.appcompat.widget.AppCompatTextView
  afkt.project.ui.widget.LoadingView -up-|> androidx.appcompat.widget.AppCompatImageView
  afkt.project.ui.widget.LoadingView o-- afkt.project.ui.widget.render.LoadingDrawable : mLoadingDrawable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
