@startuml

title __CLICK's Class Diagram__\n

  namespace dev {
    namespace callback {
      namespace click {
        class dev.callback.click.DevClickCallBack {
            + DevClickCallBack()
            + DevClickCallBack()
            + DevClickCallBack()
            + DevClickCallBack()
            + onClick()
            + onClick()
            + onClick()
            + onClick()
            + onLongClick()
            + onLongClick()
            + onLongClick()
            + onLongClick()
        }
      }
    }
  }
  

  namespace dev {
    namespace callback {
      namespace click {
        class dev.callback.click.DevDialogCallBack {
            + DevDialogCallBack()
            + DevDialogCallBack()
            + DevDialogCallBack()
            + DevDialogCallBack()
            + onDialogDestroy()
            + onDialogDismiss()
            + onDialogNotify()
            + onDialogPause()
            + onDialogResume()
            + onDialogShow()
            + onDialogStart()
            + onDialogStop()
        }
      }
    }
  }
  

  namespace dev {
    namespace callback {
      namespace click {
        class dev.callback.click.DevItemClickCallBack {
            + DevItemClickCallBack()
            + DevItemClickCallBack()
            + DevItemClickCallBack()
            + DevItemClickCallBack()
            + onItemClick()
            + onItemClick()
            + onItemClick()
            + onItemClick()
            + onItemLongClick()
            + onItemLongClick()
            + onItemLongClick()
            + onItemLongClick()
        }
      }
    }
  }
  

  dev.callback.click.DevClickCallBack -up-|> dev.callback.AbstractCommonCallBack
  dev.callback.click.DevDialogCallBack -up-|> dev.callback.click.DevClickCallBack
  dev.callback.click.DevItemClickCallBack -up-|> dev.callback.AbstractCommonCallBack


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
