@startuml

title __JSON's Class Diagram__\n

  namespace dev {
    namespace engine.json {
      class dev.engine.json.DevJSONEngine {
          {static} - sJSONEngine : IJSONEngine
          {static} + fromJson()
          {static} + fromJson()
          {static} + fromJson()
          {static} + fromJson()
          {static} + initEngine()
          {static} + isJSON()
          {static} + isJSONArray()
          {static} + isJSONObject()
          {static} + toJson()
          {static} + toJson()
          {static} + toJsonIndent()
          {static} + toJsonIndent()
          {static} + toJsonIndent()
          {static} + toJsonIndent()
          - DevJSONEngine()
      }
    }
  }
  

  namespace dev {
    namespace engine.json {
      interface dev.engine.json.IJSONEngine {
          {abstract} + fromJson()
          {abstract} + fromJson()
          {abstract} + fromJson()
          {abstract} + fromJson()
          {abstract} + isJSON()
          {abstract} + isJSONArray()
          {abstract} + isJSONObject()
          {abstract} + toJson()
          {abstract} + toJson()
          {abstract} + toJsonIndent()
          {abstract} + toJsonIndent()
          {abstract} + toJsonIndent()
          {abstract} + toJsonIndent()
      }
    }
  }
  

  namespace dev {
    namespace engine.json {
      class dev.engine.json.IJSONEngine.JSONConfig {
      }
    }
  }
  

  dev.engine.json.IJSONEngine +-down- dev.engine.json.IJSONEngine.JSONConfig


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
