@startuml

title __MVP's Class Diagram__\n

  namespace dev.base {
    namespace mvp {
      abstract class dev.base.mvp.DevBaseMVPActivity {
          # onCreate()
          # onDestroy()
          {abstract} # presenter()
          - createPresenter()
      }
    }
  }
  

  namespace dev.base {
    namespace mvp {
      abstract class dev.base.mvp.DevBaseMVPFragment {
          + onCreateView()
          + onDestroy()
          {abstract} # presenter()
          - createPresenter()
      }
    }
  }
  

  namespace dev.base {
    namespace mvp {
      class dev.base.mvp.MVP {
          - MVP()
      }
    }
  }
  

  namespace dev.base {
    namespace mvp {
      interface dev.base.mvp.MVP.IModel {
      }
    }
  }
  

  namespace dev.base {
    namespace mvp {
      interface dev.base.mvp.MVP.IPresenter {
          {abstract} + attachView()
          {abstract} + detachView()
      }
    }
  }
  

  namespace dev.base {
    namespace mvp {
      interface dev.base.mvp.MVP.IView {
      }
    }
  }
  

  namespace dev.base {
    namespace mvp {
      class dev.base.mvp.MVP.Presenter {
          + attachView()
          + detachView()
      }
    }
  }
  

  dev.base.mvp.DevBaseMVPActivity .up.|> dev.base.mvp.MVP.IView
  dev.base.mvp.DevBaseMVPActivity -up-|> dev.base.activity.DevBaseActivity
  dev.base.mvp.DevBaseMVPActivity o-- P : mPresenter
  dev.base.mvp.DevBaseMVPFragment .up.|> dev.base.mvp.MVP.IView
  dev.base.mvp.DevBaseMVPFragment -up-|> dev.base.fragment.DevBaseFragment
  dev.base.mvp.DevBaseMVPFragment o-- P : mPresenter
  dev.base.mvp.MVP +-down- dev.base.mvp.MVP.IModel
  dev.base.mvp.MVP +-down- dev.base.mvp.MVP.IPresenter
  dev.base.mvp.MVP +-down- dev.base.mvp.MVP.IView
  dev.base.mvp.MVP +-down- dev.base.mvp.MVP.Presenter
  dev.base.mvp.MVP.Presenter .up.|> dev.base.mvp.MVP.IPresenter
  dev.base.mvp.MVP.Presenter o-- M : mModel
  dev.base.mvp.MVP.Presenter o-- V : mView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
