@startuml

title __MVVM's Class Diagram__\n

  namespace afkt.project {
    namespace framework.mvvm {
      class afkt.project.framework.mvvm.ArticleMVVM {
      }
    }
  }
  

  namespace afkt.project {
    namespace framework.mvvm {
      interface afkt.project.framework.mvvm.ArticleMVVM.Model {
          {abstract} + requestArticleLists()
      }
    }
  }
  

  namespace afkt.project {
    namespace framework.mvvm {
      class afkt.project.framework.mvvm.ArticleMVVM.ModelImpl {
          + requestArticleLists()
      }
    }
  }
  

  namespace afkt.project {
    namespace framework.mvvm {
      class afkt.project.framework.mvvm.ArticleMVVM.ViewModel {
          + ViewModel()
          + getArticleLists()
      }
    }
  }
  

  namespace afkt.project {
    namespace framework.mvvm {
      class afkt.project.framework.mvvm.ArticleMVVMActivity {
          ~ whorlView : WhorlView
          + getLayoutId()
          + initListeners()
          + initOtherOperate()
          + initValues()
          + initViews()
          # onDestroy()
      }
    }
  }
  

  afkt.project.framework.mvvm.ArticleMVVM +-down- afkt.project.framework.mvvm.ArticleMVVM.Model
  afkt.project.framework.mvvm.ArticleMVVM +-down- afkt.project.framework.mvvm.ArticleMVVM.ModelImpl
  afkt.project.framework.mvvm.ArticleMVVM +-down- afkt.project.framework.mvvm.ArticleMVVM.ViewModel
  afkt.project.framework.mvvm.ArticleMVVM.ModelImpl .up.|> afkt.project.framework.mvvm.ArticleMVVM.Model
  afkt.project.framework.mvvm.ArticleMVVM.ViewModel o-- afkt.project.databinding.ActivityArticleMvvmBinding : mActivityArticleMvvmBinding
  afkt.project.framework.mvvm.ArticleMVVM.ViewModel o-- afkt.project.ui.adapter.ArticleAdapter : mArticleAdapter
  afkt.project.framework.mvvm.ArticleMVVM.ViewModel o-- afkt.project.framework.mvvm.ArticleMVVM.Model : mModel
  afkt.project.framework.mvvm.ArticleMVVMActivity -up-|> afkt.project.base.app.BaseMVVMActivity
  afkt.project.framework.mvvm.ArticleMVVMActivity o-- afkt.project.framework.mvvm.ArticleMVVM.ViewModel : viewModel


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
