@startuml

title __FRAGMENT's Class Diagram__\n

  namespace dev.base {
    namespace fragment {
      abstract class dev.base.fragment.AbstractDevBaseFragment {
          # mContentView : View
          # mContext : Context
          # mDialog : Dialog
          # mDialogFragment : DialogFragment
          # mIsFragmentVisible : boolean
          # mPopupWindow : PopupWindow
          # mTag : String
          {abstract} + contentId()
          {abstract} + contentView()
          + getContentView()
          + getDialog()
          + getDialogFragment()
          + getPopupWindow()
          + initListeners()
          + initMethodOrder()
          + initOtherOperate()
          + initValues()
          + initViews()
          + onAttach()
          + onCreate()
          + onCreateView()
          + onDestroy()
          + onDetach()
          + onHiddenChanged()
          + onPause()
          + onResume()
          + onStart()
          + onStop()
          + setDialog()
          + setDialog()
          + setDialogFragment()
          + setDialogFragment()
          + setPopupWindow()
          + setPopupWindow()
          + setUserVisibleHint()
          + showToast()
          + showToast()
          # isFragmentVisible()
          {abstract} # onInit()
          - layoutInit()
          - printLogPri()
          - printLogPri()
      }
    }
  }
  

  namespace dev.base {
    namespace fragment {
      abstract class dev.base.fragment.DevBaseFragment {
          + onClick()
      }
    }
  }
  

  dev.base.fragment.AbstractDevBaseFragment .up.|> dev.base.able.IDevBaseMethod
  dev.base.fragment.AbstractDevBaseFragment .up.|> dev.base.able.IDevBaseUIOperation
  dev.base.fragment.AbstractDevBaseFragment .up.|> dev.base.able.IDevBaseViewOperation
  dev.base.fragment.AbstractDevBaseFragment -up-|> androidx.fragment.app.Fragment
  dev.base.fragment.DevBaseFragment .up.|> android.view.View.OnClickListener
  dev.base.fragment.DevBaseFragment -up-|> dev.base.fragment.AbstractDevBaseFragment


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
