@startuml

title __ADJUST's Class Diagram__\n

  namespace dev.widget {
    namespace adjust {
      class dev.widget.adjust.AdjustHeightGridView {
          + AdjustHeightGridView()
          + AdjustHeightGridView()
          + AdjustHeightGridView()
          + AdjustHeightGridView()
          # onMeasure()
      }
    }
  }
  

  namespace dev.widget {
    namespace adjust {
      class dev.widget.adjust.AdjustHeightListView {
          + AdjustHeightListView()
          + AdjustHeightListView()
          + AdjustHeightListView()
          + AdjustHeightListView()
          # onMeasure()
      }
    }
  }
  

  namespace dev.widget {
    namespace adjust {
      class dev.widget.adjust.AdjustHeightRecyclerView {
          + AdjustHeightRecyclerView()
          + AdjustHeightRecyclerView()
          + AdjustHeightRecyclerView()
          # onMeasure()
      }
    }
  }
  

  namespace dev.widget {
    namespace adjust {
      class dev.widget.adjust.AdjustHeightWebView {
          + AdjustHeightWebView()
          + AdjustHeightWebView()
          + AdjustHeightWebView()
          + AdjustHeightWebView()
          # onMeasure()
      }
    }
  }
  

  dev.widget.adjust.AdjustHeightGridView -up-|> android.widget.GridView
  dev.widget.adjust.AdjustHeightListView -up-|> android.widget.ListView
  dev.widget.adjust.AdjustHeightRecyclerView -up-|> androidx.recyclerview.widget.RecyclerView
  dev.widget.adjust.AdjustHeightWebView -up-|> android.webkit.WebView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
