@startuml

title __STANDARD's Class Diagram__\n

  namespace dev.standard {
    class dev.standard.ColorSortMain {
        {static} + main()
    }
  }
  

  namespace dev.standard {
    class dev.standard.ColorSortMain.Builder {
        {static} - XML_CONTENT : String
        {static} + createXML()
    }
  }
  

  namespace dev.standard {
    class dev.standard.ColorSortMain.SAXXml {
        - xmlPath : String
        + analysisColorsXml()
        - SAXXml()
    }
  }
  

  namespace dev.standard {
    interface dev.standard.ColorSortMain.SAXXml.DocumentListener {
        {abstract} + OnEnd()
    }
  }
  

  namespace dev.standard {
    class dev.standard.ColorSortMain.SAXXml.SAXDemoHandel {
        - colorKey : String
        - colorValue : String
        - lists : List<ColorInfo>
        + SAXDemoHandel()
        + characters()
        + endDocument()
        + endElement()
        + startDocument()
        + startElement()
    }
  }
  

  dev.standard.ColorSortMain +-down- dev.standard.ColorSortMain.Builder
  dev.standard.ColorSortMain +-down- dev.standard.ColorSortMain.SAXXml
  dev.standard.ColorSortMain.SAXXml +-down- dev.standard.ColorSortMain.SAXXml.DocumentListener
  dev.standard.ColorSortMain.SAXXml +-down- dev.standard.ColorSortMain.SAXXml.SAXDemoHandel
  dev.standard.ColorSortMain.SAXXml.SAXDemoHandel -up-|> org.xml.sax.helpers.DefaultHandler
  dev.standard.ColorSortMain.SAXXml.SAXDemoHandel o-- dev.standard.ColorSortMain.SAXXml.DocumentListener : listener


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
