@startuml

title __WIDGET's Class Diagram__\n

  namespace dev.widget {
    class dev.widget.SlideImageView {
        - animRunnable : Runnable
        - checkTime : long
        - drawBitmap : Bitmap
        - dstRectF : RectF
        - estimateWidth : int
        - handler : Handler
        - isAllowSlide : boolean
        - isNeedSlide : boolean
        - isScrollBottom : boolean
        - isStartAnim : boolean
        - isStopAnim : boolean
        - lastX : float
        - lastY : float
        - measureCount : int
        - paint : Paint
        - scale : float
        - slideCalcScale : float
        - slideHeight : float
        - slideLenth : float
        - slideSpeed : long
        - srcRect : Rect
        - viewHeight : int
        - viewWidth : int
        + SlideImageView()
        + SlideImageView()
        + SlideImageView()
        + getCheckTime()
        + getEstimateWidth()
        + getMeasureCount()
        + getScale()
        + getSlideHeight()
        + getSlideLenth()
        + getSlideSpeed()
        + isAllowSlide()
        + isNeedSlide()
        + isScrollBottom()
        + isStartAnim()
        + onTouchEvent()
        + resizeImage()
        + resizeImageH()
        + setAllowSlide()
        + setCheckTime()
        + setEstimateWidth()
        + setMeasureCount()
        + setNeedSlide()
        + setScale()
        + setScrollDirection()
        + setSlideHeight()
        + setSlideHeightScale()
        + setSlideLenth()
        + setSlideSpeed()
        + startAnim()
        + stopAnim()
        # onDraw()
        # onMeasure()
        - calcSlideScale()
    }
  }
  

  dev.widget.SlideImageView -up-|> androidx.appcompat.widget.AppCompatImageView


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
