@startuml

title __SHARE's Class Diagram__\n

  namespace dev {
    namespace utils {
      namespace app {
        namespace share {
          interface dev.utils.app.share.IPreference {
              {abstract} + clear()
              {abstract} + contains()
              {abstract} + get()
              {abstract} + getAll()
              {abstract} + getAll()
              {abstract} + getBoolean()
              {abstract} + getFloat()
              {abstract} + getInt()
              {abstract} + getLong()
              {abstract} + getSet()
              {abstract} + getString()
              {abstract} + put()
              {abstract} + putAll()
              {abstract} + putAll()
              {abstract} + putAll()
              {abstract} + remove()
              {abstract} + removeAll()
              {abstract} + removeAll()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace share {
          enum DataType {
            BOOLEAN
            FLOAT
            INTEGER
            LONG
            STRING
            STRING_SET
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace share {
          class dev.utils.app.share.IPreferenceHolder {
              {static} - sHashMaps : HashMap<String, IPreference>
              {static} + getPreference()
              {static} + getPreference()
              {static} + getPreference()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace share {
          class dev.utils.app.share.PreferenceImpl {
              {static} - NAME : String
              - mPreferences : SharedPreferences
              + PreferenceImpl()
              + PreferenceImpl()
              + PreferenceImpl()
              + clear()
              + contains()
              + get()
              + getAll()
              + getAll()
              + getBoolean()
              + getFloat()
              + getInt()
              + getLong()
              + getSet()
              + getString()
              + put()
              + putAll()
              + putAll()
              + putAll()
              + remove()
              + removeAll()
              + removeAll()
              - getValue()
              - put()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace share {
          class dev.utils.app.share.PreferenceImpl.ComparatorImpl {
              + compare()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace share {
          class dev.utils.app.share.SPUtils {
              - SPUtils()
          }
        }
      }
    }
  }
  

  namespace dev {
    namespace utils {
      namespace app {
        namespace share {
          class dev.utils.app.share.SharedUtils {
              {static} - sContext : Context
              {static} + clear()
              {static} + contains()
              {static} + get()
              {static} + getAll()
              {static} + getAll()
              {static} + getBoolean()
              {static} + getFloat()
              {static} + getInt()
              {static} + getLong()
              {static} + getSet()
              {static} + getString()
              {static} + init()
              {static} + put()
              {static} + putAll()
              {static} + putAll()
              {static} + putAll()
              {static} + remove()
              {static} + removeAll()
              {static} + removeAll()
              - SharedUtils()
          }
        }
      }
    }
  }
  

  dev.utils.app.share.IPreference +-down- dev.utils.app.share.IPreference.DataType
  dev.utils.app.share.PreferenceImpl .up.|> dev.utils.app.share.IPreference
  dev.utils.app.share.PreferenceImpl +-down- dev.utils.app.share.PreferenceImpl.ComparatorImpl
  dev.utils.app.share.PreferenceImpl.ComparatorImpl .up.|> java.util.Comparator
  dev.utils.app.share.SPUtils -up-|> dev.utils.app.share.IPreferenceHolder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
