@startuml

title __JUMP's Class Diagram__\n

  namespace afkt.project {
    namespace ui {
      namespace widget {
        namespace render {
          namespace circle.jump {
            class afkt.project.ui.widget.render.circle.jump.DanceLoadingRenderer {
                {static} - ACCELERATE_INTERPOLATOR : Interpolator
                {static} - ANIMATION_DURATION : long
                {static} - BALL_FORWARD_END_ENTER_DURATION_OFFSET : float
                {static} - BALL_FORWARD_END_EXIT_DURATION_OFFSET : float
                {static} - BALL_FORWARD_START_ENTER_DURATION_OFFSET : float
                {static} - BALL_FORWARD_START_EXIT_DURATION_OFFSET : float
                {static} - BALL_REVERSAL_END_ENTER_DURATION_OFFSET : float
                {static} - BALL_REVERSAL_END_EXIT_DURATION_OFFSET : float
                {static} - BALL_REVERSAL_START_ENTER_DURATION_OFFSET : float
                {static} - BALL_REVERSAL_START_EXIT_DURATION_OFFSET : float
                {static} - CENTER_CIRCLE_FORWARD_END_SCALE_DURATION_OFFSET : float
                {static} - CENTER_CIRCLE_FORWARD_START_SCALE_DURATION_OFFSET : float
                {static} - CENTER_CIRCLE_REVERSAL_END_SCALE_DURATION_OFFSET : float
                {static} - CENTER_CIRCLE_REVERSAL_START_SCALE_DURATION_OFFSET : float
                {static} - DANCE_INTERVAL_ANGLE : int
                {static} - DANCE_START_ANGLE : int
                {static} - DECELERATE_INTERPOLATOR : Interpolator
                {static} - DEFAULT_CENTER_RADIUS : float
                {static} - DEFAULT_COLOR : int
                {static} - DEFAULT_DANCE_BALL_RADIUS : float
                {static} - DEFAULT_STROKE_WIDTH : float
                {static} - DEGREE_360 : int
                {static} - DIRECTION : int[]
                {static} - MATERIAL_INTERPOLATOR : Interpolator
                {static} - NUM_POINTS : int
                {static} - POINT_X : float[]
                {static} - POINT_Y : float[]
                {static} - RING_FORWARD_END_ROTATE_DURATION_OFFSET : float
                {static} - RING_FORWARD_START_ROTATE_DURATION_OFFSET : float
                {static} - RING_REVERSAL_END_ROTATE_DURATION_OFFSET : float
                {static} - RING_REVERSAL_START_ROTATE_DURATION_OFFSET : float
                {static} - RING_START_ANGLE : int
                - mArcColor : int
                - mCenterRadius : float
                - mColor : int
                - mCurrentBounds : RectF
                - mDanceBallRadius : float
                - mPaint : Paint
                - mRotation : float
                - mScale : float
                - mShapeChangeHeight : float
                - mShapeChangeWidth : float
                - mStrokeInset : float
                - mStrokeWidth : float
                - mTempBounds : RectF
                # computeRender()
                # draw()
                # reset()
                # setAlpha()
                # setColorFilter()
                - DanceLoadingRenderer()
                - getDanceBallRadius()
                - getRotation()
                - halfAlphaColor()
                - init()
                - setColor()
                - setDanceBallRadius()
                - setInsets()
                - setRotation()
                - setupPaint()
            }
          }
        }
      }
    }
  }
  

  namespace afkt.project {
    namespace ui {
      namespace widget {
        namespace render {
          namespace circle.jump {
            class afkt.project.ui.widget.render.circle.jump.DanceLoadingRenderer.Builder {
                - mContext : Context
                + Builder()
                + build()
            }
          }
        }
      }
    }
  }
  

  afkt.project.ui.widget.render.circle.jump.DanceLoadingRenderer -up-|> afkt.project.ui.widget.render.LoadingRenderer
  afkt.project.ui.widget.render.circle.jump.DanceLoadingRenderer +-down- afkt.project.ui.widget.render.circle.jump.DanceLoadingRenderer.Builder


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
